window.SHORTS_SHOWCASE_DATA = {
  "motivation": {
    "zh": "本作品集以商用車產品企劃可面對的顧客溝通場景為起點，將短影音視為市場洞察、品牌記憶與產品價值轉譯的介面。台灣的城市配送、營建補給、旅運接駁、福祉移動與長途行車安全，常由商用車在清晨、夜間與高壓路段中維持運作；國際市場則同時面對淨零轉型、AI安全輔助、車隊成本與高齡社會需求。若品牌敘事能把工程技術、服務可靠度、駕駛健康、乘客尊嚴與企業治理放入同一條顧客旅程，影片便能協助潛在客戶理解商用車的社會與經濟價值。這套網站以 AIDTAS、STP 與品牌權益觀點組織內容，先以影像吸引注意，再透過情境文案建立信任，最後把觀看轉化為可討論的商品企劃議題、數位行銷素材與 B2B 溝通資產。其目的在於展示一種兼具資料判讀、分眾溝通、服務設計與公共責任的企劃能力，使商用車被理解為城市韌性、產業效率與照護倫理中的關鍵節點之一。",
    "en": "This portfolio begins with customer-communication scenarios relevant to commercial vehicle product planning at Hotai Motor. Short videos are treated as interfaces that translate market insight, brand memory, engineering reliability, driver wellbeing, passenger dignity, fleet cost, and public value into a sequence that B2B audiences can discuss. In Taiwan, delivery, construction supply, shuttle service, welfare mobility, and long-distance safety depend on commercial vehicles across early mornings, nights, and demanding road conditions. In global markets, net-zero transition, AI-assisted safety, fleet governance, and ageing societies reshape the same questions. Using AIDTAS, STP, and customer-based brand equity perspectives, the site connects visual attention, contextual copy, trust building, and portfolio evidence into a practical communication asset.",
    "ja": "本作品集は、商用車商品企画が向き合う顧客コミュニケーションの場面を起点にしている。ショート動画を、市場洞察、ブランド記憶、技術信頼性、ドライバーの健康、乗客の尊厳、車隊コスト、公共価値を翻訳するインターフェースとして扱う。台湾では、配送、建設補給、送迎、福祉移動、長距離安全が、早朝や夜間、高負荷の道路条件の中で商用車に支えられている。国際市場では、ネットゼロ、AI支援安全、車隊ガバナンス、高齢社会が同じ課題を変化させている。本サイトは AIDTAS、STP、顧客ベースのブランド・エクイティを参照し、視覚的注意、情境文案、信頼形成、商品企画資料を結びつける。"
  },
  "i18n": {
    "zh": {
      "langName": "中文",
      "copyright": "Copyright © 2026 張義豊(Yi-Li, Chang) All Rights Reserved.",
      "brand": "商用車產品企劃短影音作品集",
      "heroKicker": "PROTOTYPE SIMULATION｜9:16 YouTube Shorts Showcase",
      "heroTitle": "商用車短影音互動式作品集",
      "heroLead": "以商用車產品企劃、數位行銷與品牌溝通為核心，串聯城市物流、車隊成本、家庭安全、福祉移動、氣候責任與長途行車安全科技。",
      "enter": "進入旋轉櫥窗",
      "openHeroImage": "點擊放大插圖",
      "sectionMotivation": "創作動機",
      "motivationKicker": "CREATIVE MOTIVE",
      "motivationTitle": "以短影音建立商用車產品企劃的顧客溝通介面",
      "showMore": "顯示更多",
      "showLess": "收合內容",
      "sectionShowcase": "旋轉櫥窗",
      "sectionTopics": "主題索引",
      "sectionStory": "企劃敘事",
      "sectionTech": "互動規格",
      "prev": "上一支",
      "next": "下一支",
      "fullscreen": "全螢幕",
      "restore": "還原",
      "volume": "音量",
      "muted": "靜音",
      "unmuted": "開啟聲音",
      "openYoutube": "前往 YouTube 觀看影片",
      "copyTitle": "複製標題",
      "copyCaption": "複製文案",
      "copyTags": "複製 hashtags",
      "theme": "版型",
      "language": "語言",
      "toc": "目錄",
      "close": "關閉",
      "reasonHeading": "為何如此設計影片",
      "titleHeading": "Title",
      "captionHeading": "文案 / Caption",
      "hashtagsHeading": "Hashtags",
      "storyTitle": "從短影音觀看到商用車產品企劃",
      "storyText": "本網站將每支短影音視為一個顧客場景入口：先由 9:16 影像形成注意，再由標題、三語文案與設計說明連回市場區隔、任務適配、服務可靠度、品牌信任與公共價值。",
      "techTitle": "靜態互動網站規格",
      "techText": "採用純靜態 HTML、CSS、Vanilla JavaScript；包含旋轉櫥窗、直接主題切換、YouTube iframe 全螢幕、音量參數切換、三語介面、四版型、Floating controls、Floating TOC 與鍵盤可及性。",
      "glossary": "名詞解釋",
      "copied": "已複製",
      "invalidUrl": "尚未偵測到有效 YouTube 影片 ID"
    },
    "en": {
      "langName": "EN",
      "copyright": "Copyright © 2026 張義豊(Yi-Li, Chang) All Rights Reserved.",
      "brand": "Commercial Vehicle Product Planning Shorts Portfolio",
      "heroKicker": "PROTOTYPE SIMULATION｜9:16 YouTube Shorts Showcase",
      "heroTitle": "Interactive Commercial Vehicle Shorts Portfolio",
      "heroLead": "A digital marketing and brand-communication showcase for commercial vehicle product planning, connecting urban logistics, fleet economics, family safety, welfare mobility, climate responsibility, and long-distance safety technology.",
      "enter": "Enter Showcase",
      "openHeroImage": "Click to enlarge illustration",
      "sectionMotivation": "Creative Motive",
      "motivationKicker": "CREATIVE MOTIVE",
      "motivationTitle": "Building a customer-communication interface for commercial vehicle planning",
      "showMore": "Show more",
      "showLess": "Show less",
      "sectionShowcase": "Rotating Showcase",
      "sectionTopics": "Topic Index",
      "sectionStory": "Planning Narrative",
      "sectionTech": "Interaction Spec",
      "prev": "Previous",
      "next": "Next",
      "fullscreen": "Fullscreen",
      "restore": "Restore",
      "volume": "Volume",
      "muted": "Muted",
      "unmuted": "Sound on",
      "openYoutube": "Watch on YouTube",
      "copyTitle": "Copy title",
      "copyCaption": "Copy caption",
      "copyTags": "Copy hashtags",
      "theme": "Theme",
      "language": "Language",
      "toc": "Contents",
      "close": "Close",
      "reasonHeading": "Why this video is designed this way",
      "titleHeading": "Title",
      "captionHeading": "Caption",
      "hashtagsHeading": "Hashtags",
      "storyTitle": "From short-video viewing to commercial vehicle product planning",
      "storyText": "Each short functions as a customer-scenario gateway: a 9:16 visual hook creates attention, while the title, trilingual copy, and rationale connect the film to segmentation, task fit, service reliability, brand trust, and public value.",
      "techTitle": "Static interactive website specification",
      "techText": "Built with static HTML, CSS, and Vanilla JavaScript; includes a rotating showcase, direct topic switching, YouTube iframe fullscreen, volume parameter toggle, trilingual UI, four visual themes, floating controls, floating TOC, and keyboard accessibility.",
      "glossary": "Glossary",
      "copied": "Copied",
      "invalidUrl": "No valid YouTube video ID detected"
    },
    "ja": {
      "langName": "日本語",
      "copyright": "著作権所有 © 2026 張義豊(Yi-Li, Chang) 無断転載を禁じます。",
      "brand": "商用車商品企画 Shorts ポートフォリオ",
      "heroKicker": "PROTOTYPE SIMULATION｜9:16 YouTube Shorts Showcase",
      "heroTitle": "商用車ショート動画インタラクティブ作品集",
      "heroLead": "商用車の商品企画、デジタルマーケティング、ブランド・コミュニケーションを軸に、都市物流、車隊コスト、家族の安全、福祉移動、気候責任、長距離安全技術をつなぐ展示サイトです。",
      "enter": "展示を見る",
      "openHeroImage": "イラストを拡大",
      "sectionMotivation": "創作動機",
      "motivationKicker": "CREATIVE MOTIVE",
      "motivationTitle": "商用車企画の顧客コミュニケーション接点をつくる",
      "showMore": "もっと見る",
      "showLess": "閉じる",
      "sectionShowcase": "回転ショーケース",
      "sectionTopics": "テーマ索引",
      "sectionStory": "企画ナラティブ",
      "sectionTech": "インタラクション仕様",
      "prev": "前へ",
      "next": "次へ",
      "fullscreen": "全画面",
      "restore": "元に戻す",
      "volume": "音量",
      "muted": "ミュート",
      "unmuted": "音声オン",
      "openYoutube": "YouTube で見る",
      "copyTitle": "タイトルをコピー",
      "copyCaption": "文案をコピー",
      "copyTags": "Hashtags をコピー",
      "theme": "版型",
      "language": "言語",
      "toc": "目次",
      "close": "閉じる",
      "reasonHeading": "この映像設計の意図",
      "titleHeading": "Title",
      "captionHeading": "文案 / Caption",
      "hashtagsHeading": "Hashtags",
      "storyTitle": "ショート動画から商用車商品企画へ",
      "storyText": "各ショート動画を顧客シナリオの入口として扱います。9:16 の視覚的フックで注意を形成し、タイトル、三語文案、設計意図を市場区分、タスク適合、サービス信頼性、ブランド信頼、公共価値へ接続します。",
      "techTitle": "静的インタラクティブ仕様",
      "techText": "純静的 HTML、CSS、Vanilla JavaScript で構築。回転ショーケース、テーマ直接切替、YouTube iframe 全画面、音量パラメータ切替、三語 UI、四つの版型、Floating controls、Floating TOC、キーボード操作に対応します。",
      "glossary": "用語解説",
      "copied": "コピーしました",
      "invalidUrl": "有効な YouTube 動画 ID が見つかりません"
    }
  },
  "videos": [
    {
      "id": "v01-4am-city",
      "serial": "01",
      "batch": "第一批影片",
      "group": "Urban Systems",
      "titleZh": "①《凌晨4點的城市》",
      "titleEn": "① The City at 4AM",
      "titleJa": "① 朝4時の街",
      "uploadTitle": "4AM City Still Moves｜見えない時間が流れる｜Who Builds Your Morning Before Sunrise?",
      "caption": "At 4AM, the city does not reset; it transitions into a different operational mode.\nWhen visibility decreases, coordination depends more on timing, repetition, and system memory.\nVO: “Before the city wakes, something is already in motion.”\nこの時間帯では、人の意識よりもシステムの連続性が優先される。\n配送、補充、移動は、それぞれ独立しているように見えながら、\n時間と空間の制約の中で相互に影響し合う。\nVO: 「街が目覚める前に、すでに動いているものがある。」\n這段時間的運作，並不只是「提前開始」，\n而是一種維持日間秩序成立的前置條件。\nWhen supply chains synchronize correctly, the city appears seamless.\nWhen they don’t, disruptions surface hours later.\n見えない時間の積み重ねは、\n結果として「當下的順暢感」被感知，而非過程本身。",
      "hashtags": "#4AMCity #UrbanSystems #InvisibleLabor #SupplyChain #CityLogistics #MobilityFlow #UrbanRhythm #HiddenWork #SmartCities #Infrastructure #LogisticsLife #CityDynamics #SystemThinking #DailyOperations",
      "reasonZh": "資料支持：城市物流、補貨、清運與早班運輸常在低能見度時段維持基本供給，本片以「凌晨」作為供應鏈前置作業的情境入口。合理推論：在服務設計與顧客旅程理論中，消費者多半看見終端體驗，較少感知背後的節點協調，因此影像把日常順暢感連回不可見勞動與系統記憶。規劃假設：商用車品牌若能呈現城市運作背後的時間秩序，可提高公共信任與 B2B 採購者對營運可靠性的理解。行動建議：發布時可搭配「城市醒來以前」系列短文，並標示 Prototype Communication，作為作品集內的產業敘事示範。",
      "youtubeId": "wpgnXT8ieDQ",
      "url": "https://youtube.com/shorts/wpgnXT8ieDQ"
    },
    {
      "id": "v02-last-mile",
      "serial": "02",
      "batch": "第一批影片",
      "group": "Logistics Network",
      "titleZh": "②《最後一公里》",
      "titleEn": "② The Last Mile",
      "titleJa": "② 最後の一キロ",
      "uploadTitle": "Last Mile Is a System｜距離ではなく構造｜Why Final Delivery Shapes Everything",
      "caption": "The last mile is often framed as distance, but operationally it behaves as a constraint network.\nTime windows, road density, human behavior, and infrastructure overlap.\nVO: “The last mile is not the shortest — it is the most complex.”\n最終区間では、効率は単一要因では決まらない。\n複数の条件が同時に作用し、予測の難しさが増加する。\nVO: 「最後の一キロは、距離ではなく、条件の重なりだ。」\n配送の遅延は単一原因ではなく、\n小さな摩擦の累積として現れる。\nSmall inefficiencies compound, forming nonlinear delays.\nA narrow street, a missed signal, a human decision — each alters the system.\nこの区間は終点ではなく、\n全体構造の中で最も敏感な接点として機能する。",
      "hashtags": "#LastMile #DeliverySystem #UrbanLogistics #MobilityDesign #TransportTech #CityEfficiency #SupplyChainOps #LogisticsAI #SmartTransport #UrbanPlanning #SystemDynamics #FinalMile #DeliveryNetwork #Operations",
      "reasonZh": "資料支持：最後一公里配送牽涉路網密度、停靠限制、人流、時窗與客戶端接收條件，屬於高摩擦的營運場景。合理推論：依服務藍圖與作業管理觀點，配送延誤通常由多個微小節點累積，而非單一事件完全決定；影片因此以窄路、訊號、臨停與人為判斷構成複合壓力。規劃假設：若將商用車放在都市約束網絡中呈現，車型規劃便能從車輛規格延伸到任務適配。行動建議：可於網站加入 Demo Dataset 或 Prototype Simulation 的路線摩擦指標，並加註 Requires human review。",
      "youtubeId": "jfGXo2Gwook",
      "url": "https://youtube.com/shorts/jfGXo2Gwook"
    },
    {
      "id": "v03-climate",
      "serial": "03",
      "batch": "第一批影片",
      "group": "Sustainability",
      "titleZh": "③《氣候與選擇》",
      "titleEn": "③ Climate and Choice",
      "titleJa": "③ 気候と選択",
      "uploadTitle": "Climate Shapes Decisions｜環境が選択を変える｜Every Route Carries a Hidden Cost",
      "caption": "Climate is often treated as background, yet in mobility systems it functions as a constraint layer.\nEnergy use, emissions, and routing decisions are interdependent.\nVO: “Every route carries a cost — some are just delayed.”\n気候条件は単なる外部要因ではなく、\n選択の範囲と結果の分布を変化させる要素となる。\nVO: 「すべてのルートにはコストがある、ただ見えにくいだけだ。」\n短期的な効率が、長期的な負荷へと変換される場合、\nその影響は時間差をもって現れる。\nWhen decisions optimize for speed alone,\nexternalities tend to shift across time and geography.\n環境は背景ではなく、\n決定プロセスの一部として組み込まれている。",
      "hashtags": "#ClimateImpact #GreenMobility #SustainableTransport #EcoLogistics #FutureCities #CarbonCost #ESGTransport #MobilityFuture #UrbanSustainability #EnergyEfficiency #ClimateSystems #SmartMobility #TransportInnovation #NetZero",
      "reasonZh": "資料支持：能源使用、排放、路線安排與車隊更新，均與氣候議題、ESG 管理及總持有成本評估相連。合理推論：若短期效率指標未納入外部成本，決策結果可能在未來以碳成本、法規壓力或品牌風險形式回返。規劃假設：影片以氣候作為決策層，而非背景裝飾，可使商用車作品集接近國際車業在電動化、低碳供應鏈與責任採購上的討論語境。行動建議：搭配碳排與能源情境儀表板時，應明確標示 Simulated data 與資料來源限制，避免把概念展示誤讀為正式預測。",
      "youtubeId": "vZBDENK2RLg",
      "url": "https://youtube.com/shorts/vZBDENK2RLg"
    },
    {
      "id": "v04-hidden-costs",
      "serial": "04",
      "batch": "第一批影片",
      "group": "TCO & Decisions",
      "titleZh": "④《看不見的成本與決策的重量》",
      "titleEn": "④ Hidden Costs and the Weight of Decisions",
      "titleJa": "④ 見えないコストと判断の重み",
      "uploadTitle": "Hidden Costs, Heavy Decisions｜見えないコストと判断の重み｜How One Choice Shapes a System",
      "caption": "Cost begins as a number, then moves through time, routes, maintenance, downtime, and human judgment.\nVO: “What you don’t track can still shape every decision.”\n見えないコストは、日々の運用の中で少しずつ蓄積され、\nひとつの判断が複数の結果へ広がっていく。\nVO: 「見えない負担が、判断の重さを変えていく。」\n在商用車與物流營運中，成本、效率、風險、時間與服務品質彼此牽動。\n一個短期看似合理的選擇，經過車隊規模、路線安排、維修頻率與停駛風險放大後，可能改寫整體績效。\nWhen one parameter shifts, the system responds.\nLoad, timing, route, maintenance, and risk all begin to reconfigure.\n決策的重量，往往來自後續連鎖變化。\n看見成本，只是開始；理解成本如何流動，才有機會做出更穩健的判斷。",
      "hashtags": "#HiddenCosts #DecisionMaking #FleetManagement #MobilityStrategy #OperationalEfficiency #SystemThinking #LogisticsPlanning #CostAnalysis #BusinessStrategy #TransportEconomics #RiskAnalysis #DataDrivenDecision #OperationsManagement #FleetStrategy",
      "reasonZh": "資料支持：車隊成本通常包含購置、油電、維修、保險、折舊、停駛與人力排班等項目，單看購車價格容易低估長期影響。合理推論：依 TCO 與系統動態觀點，一個參數變化會透過路線、維保與服務品質產生連鎖效果。規劃假設：本片以「看不見的成本」連接財務分析與商品企劃，可讓面試者展現跨部門語言能力，包含業務、售後、財務與車隊端。行動建議：作品集內若加入成本試算器，需標示 Demo Dataset／Prototype Simulation／Requires human review，並將結果定位為決策輔助。",
      "youtubeId": "4u1jqEhYpUI",
      "url": "https://youtube.com/shorts/4u1jqEhYpUI"
    },
    {
      "id": "v05-family",
      "serial": "05",
      "batch": "第一批影片",
      "group": "Family Mobility",
      "titleZh": "⑤《一家人的方向》",
      "titleEn": "⑤ A Family Direction",
      "titleJa": "⑤ 家族の方向",
      "uploadTitle": "Family Direction, Shared Safety｜家族の行き先は時間の中にある｜Where Safety Becomes Shared Time",
      "caption": "A family journey begins before the road appears. Bags, toys, food, small routines, and safety checks gradually become one shared preparation.\nVO: “Some journeys carry more than luggage.”\n朝の準備は、移動の始まりであると同時に、家族の時間を整える小さな設計でもある。荷物を積み、シートベルトを確認し、視線を交わす。その一つ一つが、安心の条件を静かに作っていく。\nVO: 「行き先よりも、同じ方向を向く時間が残っていく。」\n家庭移動的價值，通常不只由目的地決定。若車內空間能容納行李、兒童活動、安全拘束與長時間乘坐需求，移動過程便較容易轉化為穩定的共同經驗。\nWhen the road opens toward mountains and evening light, the vehicle becomes a temporary frame for trust, care, and continuity. The destination matters, yet the more durable memory may be the rhythm a family learns to share along the way.\n家族の方向は、地図上の一点だけで測られるものではない。移動の途中で積み重なる表情、沈黙、風景、そして安全への配慮が、次の記憶の輪郭をつくる。",
      "hashtags": "#FamilyMobility #SUVLife #SharedTime #RoadSafety #FamilyTravel #LifestyleMobility #WeekendJourney #HumanCenteredDesign #ToyotaInspired #OutdoorLife #SafeDriving #CinematicSUV #MobilityDesign #YouTubeShorts",
      "reasonZh": "資料支持：家庭用車購買決策通常受到安全、空間、乘坐舒適、行李承載與生活情境共同影響，本片將這些因素轉為清晨準備、繫安全帶、裝載與抵達自然場景的敘事。合理推論：依 Jobs-to-be-Done 與品牌情感連結理論，SUV 的價值可由「完成家庭外出任務」與「形成可記憶的共同時間」兩條線索共同支撐。規劃假設：若商用車作品集納入家庭安全語境，可把車輛企劃能力延伸到乘用市場與生活方式研究。行動建議：標題與 hashtags 保留國際平台可讀性，影像素材需持續去品牌化並維持交通合規。",
      "youtubeId": "YJ-nrJlotlU",
      "url": "https://youtube.com/shorts/YJ-nrJlotlU"
    },
    {
      "id": "v06-backbone",
      "serial": "06",
      "batch": "第一批影片",
      "group": "Urban Resilience",
      "titleZh": "⑥《沒有它，城市停止》",
      "titleEn": "⑥ Without It, the City Stops",
      "titleJa": "⑥ それがなければ都市は止まる",
      "uploadTitle": "Remove One Layer, System Fails｜それがなければ都市は止まる｜The Invisible Backbone of Cities",
      "caption": "Urban systems are often perceived through visible activity,\nyet their stability depends on layers that are rarely noticed.\nVO: “If one layer stops, everything slows.”\n都市の機能は、表に見える部分だけでは成立しない。\n見えない基盤が連続的に支えている。\nVO: 「それが止まれば、都市は動かない。」\n物流、補給、運輸網之間存在依存關係，\n其中任何一個節點出現問題，都可能影響整體。\nInfrastructure operates through interdependence.\nFailure is rarely isolated; it propagates.\n城市的穩定，不來自單一系統，\n而來自多層結構的持續協調。",
      "hashtags": "#UrbanInfrastructure #CitySystems #MobilityNetwork #SmartCities #TransportSystems #LogisticsNetwork #UrbanFlow #SystemFailure #InfrastructureDesign #CityDynamics #MobilityFuture #UrbanPlanning #ConnectedSystems #ResilientCities",
      "reasonZh": "資料支持：城市機能由補給、物流、公共服務、維修、清運與通勤節點共同支撐，其中任一層失衡，都可能使後續流程出現延遲。合理推論：以韌性城市與基礎設施研究視角觀察，商用車不只承載貨物，也承載制度運作中的時間承諾。規劃假設：影片透過「移除一層」的情境，能讓觀眾理解商用車在城市連續性中的必要位置，同時避免直接銷售語氣。行動建議：可與「城市系統論」主題頁連動，加入節點依存關係示意圖，並把所有分析標示為規劃假設而非官方營運數據。",
      "youtubeId": "3x3ra3L4rR4",
      "url": "https://youtube.com/shorts/3x3ra3L4rR4"
    },
    {
      "id": "v07-time-value",
      "serial": "07",
      "batch": "第二批影片",
      "group": "Executive Mobility",
      "titleZh": "①《時間的價值》",
      "titleEn": "① The Value of Time",
      "titleJa": "① 時間の価値",
      "uploadTitle": "Time Can Be Reclaimed｜時間を取り戻す移動｜GRANVIA, Space for Decisions Under Pressure",
      "caption": "Time in cities is not simply spent; it is often fragmented by noise, interruptions, and competing demands.\n“Time is never really lost. Only taken… by everything around you.”\n移動中的空間，若能降低干擾密度，思考節奏通常比較容易維持，判斷也較可能在較完整的注意力條件下形成。這支影片關注的，不只是商務移動的舒適感，而是空間控制如何影響決策品質。\n都市の時間圧力は、速度だけでは調整しにくい。\n「時間は失われるものではない。奪われるか、取り戻すかだ。」\nWhen movement becomes a controlled environment, mobility can function as a buffer rather than a burden. 於是，車內不只是移動場域，也可能成為把碎裂時間重新整理的暫時介面。",
      "hashtags": "#ExecutiveMobility #BusinessTravel #TimeManagement #DecisionMaking #MobilityDesign #PremiumVan #ProductivitySpace #UrbanMobility #BusinessLifestyle #TransportInnovation #ToyotaInspired #LuxuryTransport #ShortFilmConcept #YouTubeShorts",
      "reasonZh": "資料支持：商務移動常面臨碎片化時間、資訊干擾與高壓決策需求，車內空間配置會影響注意力、休息品質與工作銜接。合理推論：依顧客旅程與場景化品牌管理，頂級廂型車可被敘述為「移動中的決策介面」，使舒適性與效率需求建立可感知連結。規劃假設：若以時間管理而非豪華炫示作為主軸，作品集能呈現更接近企業客戶採購語言的價值論述。行動建議：影片發布文案應將「壓力下的空間控制」作為主題，相關生產力效益若使用數字，須標示 Prototype Simulation 與 Requires human review。",
      "youtubeId": "PTwo1G_eg8I",
      "url": "https://youtube.com/shorts/PTwo1G_eg8I"
    },
    {
      "id": "v08-city-hands",
      "serial": "08",
      "batch": "第二批影片",
      "group": "Commercial Van",
      "titleZh": "②《城市的手》",
      "titleEn": "② The Hand of the City",
      "titleJa": "② 街を動かす手",
      "uploadTitle": "Invisible Hands Move Cities｜見えない手が街を動かす｜HIACE Before the Morning Begins",
      "caption": "A city may look calm before sunrise, yet many of its daytime functions depend on work already underway.\n“Before the city wakes… someone is already moving.”\n凌晨時段的配送、補貨與短程載運，通常分散在不同節點進行。若這些節點之間維持基本同步，白天的餐飲、零售與工地流程就比較容易呈現順暢；若其中某處延誤，影響常會沿著時間往後傳遞，而不一定在當下立刻被看見。\n都市の連続性は、目立つ中心だけで成立するわけではない。\n「街が動く前に、誰かが動いている。」\nWhat appears ordinary later in the day is often made possible by labor that remains structurally unnoticed. 這支影片想處理的，是「日常如何被預先準備」這個問題，而不只是勞動的表面畫面。",
      "hashtags": "#HIACE #UrbanLogistics #InvisibleLabor #CitySystems #SupplyChain #DeliveryNetwork #CommercialVan #UrbanInfrastructure #MobilitySystem #TransportDesign #FleetOperations #MorningLogistics #ToyotaInspired #YouTubeShorts",
      "reasonZh": "資料支持：商用廂型車在清晨補貨、餐飲配送、工地材料與小型企業營運中具備高頻出現特徵。合理推論：從品牌資產與服務主導邏輯觀察，車輛的功能價值常由其支持的服務結果被感知，而非由車身本身單獨產生。規劃假設：以「城市的手」指稱短程載運與補給角色，有助於把 HIACE 類車型放進都市微型物流與中小企業韌性的分析框架。行動建議：Hashtags 同時納入 UrbanLogistics、SupplyChain 與 FleetOperations，可兼顧演算法分類與專業讀者辨識。",
      "youtubeId": "UhgCk6iL9G0",
      "url": "https://youtube.com/shorts/UhgCk6iL9G0"
    },
    {
      "id": "v09-shared-distance",
      "serial": "09",
      "batch": "第二批影片",
      "group": "Group Travel",
      "titleZh": "③《一起的距離》",
      "titleEn": "③ Distance Together",
      "titleJa": "③ 共に進む距離",
      "uploadTitle": "Shared Distance, Shared Time｜同じ時間を進む距離｜COASTER and the Shape of Group Travel",
      "caption": "Distance changes when it is experienced collectively. The shift is not only spatial; it also affects tempo, attention, and coexistence.\n“We don’t travel alone.”\n群體移動的特徵，不一定表現在熱烈互動。更多時候，它呈現為多個個體在同一段路程、同一套停靠節奏、同一個空間邊界中並行。這種共在，未必要被浪漫化理解；在不少情境下，它更接近一種安靜而穩定的時間共享。\n乗客が会話しなくても、移動経験は個別のままでは終わらない。\n「言葉がなくても、同じ時間を進んでいる。」\nShared transport can therefore be read as a social form with low-intensity connection. 這支影片關心的是：當移動由個人單位轉為群體單位時，距離感如何連同等待感、節奏感與在場感一起改變。",
      "hashtags": "#COASTER #GroupTravel #SharedMobility #PassengerExperience #BusLife #TransportCulture #MobilityDesign #PublicTransport #RoadTripFilm #HumanMobility #TravelTogether #ToyotaInspired #CinematicShorts #YouTubeShorts",
      "reasonZh": "資料支持：中小型巴士與團體移動涉及乘客共處、停靠節奏、座位安排、安全上下車與行程管理。合理推論：依體驗經濟與社會設計觀點，群體交通的價值不只來自運輸效率，也來自低強度連結、共享等待與共同抵達的心理秩序。規劃假設：將 COASTER 類車型放入「共享時間」語境，可拓展旅運、校外教學、企業接駁與社區照護等應用場景。行動建議：影片說明可避免過度煽情，改以乘客體驗與營運穩定性作為主軸，保持商用車企劃的專業可信度。",
      "youtubeId": "3Sppjq3REA0",
      "url": "https://youtube.com/shorts/3Sppjq3REA0"
    },
    {
      "id": "v10-accessible",
      "serial": "10",
      "batch": "第二批影片",
      "group": "Inclusive Design",
      "titleZh": "④《被看見的世界》",
      "titleEn": "④ The World That Becomes Visible",
      "titleJa": "④ 見えるようになる世界",
      "uploadTitle": "Design Changes What Can Be Reached｜届く世界は設計で変わる｜Welfare Mobility and Human Dignity",
      "caption": "Access is often described as assistance, but many barriers begin earlier, in layout, height, slope, timing, and interface design.\n“The world was not built the same for everyone.”\n當環境的預設條件與使用者狀態不相配時，阻礙常被誤讀成個體能力問題。若把動線、升降平台、固定系統與視線高度納入整體設計，許多摩擦其實可以在前端被降低，而不必把「被幫助」當成唯一敘事。\n可及性は、善意だけで安定するものではなく、構造の調整とも関わっている。\n「違うのは人じゃない。設計だ。」\nThis film frames mobility not as charity, but as a design responsibility distributed across the system. 因此，福祉車的價值，與其說是額外功能，不如說是讓不同身體條件得以進入同一社會節奏的具體安排。",
      "hashtags": "#AccessibleMobility #InclusiveDesign #WelfareVehicle #UniversalDesign #HumanCenteredDesign #MobilityForAll #AssistiveTransport #SocialInclusion #TransportEquity #AccessibleTravel #ToyotaInspired #DesignEthics #CinematicStorytelling #YouTubeShorts",
      "reasonZh": "資料支持：福祉車與可及性設計涉及升降平台、固定裝置、動線、地板高度、照護者操作與乘客尊嚴等多重條件。合理推論：依通用設計與服務公平觀點，移動障礙常由環境與介面配置放大；若前端設計降低摩擦，使用者能以較穩定方式參與日常社會節奏。規劃假設：影片以「被看見」作為主題，能把產品功能提升到公共價值與品牌責任層次。行動建議：文案應明確區分情感敘事與產品承諾，任何安全或輔具效果描述均需人工審核，並符合在地法規與實車規格。",
      "youtubeId": "ltifvJzH5rs",
      "url": "https://youtube.com/shorts/ltifvJzH5rs"
    },
    {
      "id": "v11-watches-back",
      "serial": "11",
      "batch": "第二批影片",
      "group": "Safety Technology",
      "titleZh": "⑤《長途駕駛與行車安全科技》",
      "titleEn": "⑤ Long-Distance Driving and Safety Technology",
      "titleJa": "⑤ 長距離運転と安全技術",
      "uploadTitle": "The System That Watches Back｜見えない疲労を見守る｜Long Distance Safety",
      "caption": "Long-distance driving can look steady from outside the vehicle, while attention may already be moving through fatigue, delayed reaction, and small corrections that the driver has not yet recognized.\n“You trust your instincts. But your instincts fade before you notice.”\n長距離運転では、疲労は突然の出来事として現れるとは限らない。まばたきの間隔、車線内の揺れ、姿勢の変化、前方車両との距離感が、事故の前段階として少しずつ重なっていく。\n「見えない疲れを、システムは先に見つける。」\n本片將長途駕駛放在人因工程、ADAS 輔助、安全距離管理與車隊風險治理的交會處。前半段以清晨高速道路、疲勞訊號、微幅車道偏移與低干擾 HUD 呈現人體限度；後半段轉向穩定車距、協調車流、預測性減速與紅燈前平順停車，使安全從單點提醒擴展為連續控制。\nWhen a small drift begins, the outcome is shaped by workload, circadian rhythm, road condition, visibility, following distance, traffic flow, and system response. The system watches, but it still needs the driver.\nDistance is not reaction. It is prevention. Control is shared. Timing is managed before it becomes risk. Safety is human judgment, system awareness, and operational discipline working within the same field.\nThis concept is a safety communication prototype. ADAS and AI-assisted driving are presented as supportive layers that require human responsibility, fleet policy, driver training, and human review.",
      "hashtags": "#RoadSafety #ADAS #FatigueDetection #DriverMonitoring #LongDistanceDriving #AccidentPrevention #FleetSafety #CommercialVehicleSafety #HumanFactors #RiskManagement #SafeFollowingDistance #PredictiveSafety #SmartMobility #YouTubeShorts",
      "reasonZh": "資料支持：長途駕駛的事故風險通常與疲勞、注意力下降、車道偏移、跟車距離、道路環境、能見度、工時安排與車隊管理共同相關；ADAS、駕駛監測與安全距離維持可作為風險降低的輔助層。合理推論：依人因工程、Swiss Cheese Model、服務藍圖與品牌風險溝通觀點，事故預防需要將個人警覺、車輛感測、企業排班、教育訓練與道路條件放入同一控制場域。規劃假設：前半段以低飽和藍灰色呈現隱性疲勞，後半段改以穩定車距與協調車流呈現預防式安全，可避免把安全科技拍成誇張科幻效果，也能提升商用車作品集在車隊管理、保險風險與 ESG 安全責任上的可信度。行動建議：所有 AI／ADAS 敘述須標示 Prototype Simulation / Requires human review，並清楚說明系統屬輔助機制，仍需駕駛責任與企業治理配套。",
      "youtubeId": "yC4NirTkge4",
      "url": "https://youtube.com/shorts/yC4NirTkge4"
    },
    {
      "id": "v12-distance-health",
      "serial": "12",
      "batch": "第二批影片",
      "group": "Driver Wellbeing",
      "titleZh": "⑥《長途駕駛下的健康意識》",
      "titleEn": "⑥ Health Awareness in Long-Distance Driving",
      "titleJa": "⑥ 長距離運転における健康意識",
      "uploadTitle": "The Distance You Don't See｜見えない疲労の距離｜Long Driving, Human Limits, and Safer Arrival",
      "caption": "Long-distance driving may look like one continuous route, yet the body experiences it as accumulated load. Blinking slows, attention narrows, hands tighten, reaction time stretches, and the risk surface begins to change before danger is fully visible.\n“You think you're just driving. But your body is already keeping score.”\n長距離運転では、疲労は一つの瞬間だけで説明しにくい。姿勢、呼吸、視線、乾き、循環、反応の遅れが重なり、見えない距離として身体の中に蓄積されていく。\n「疲れは、気づく前に距離になる。」\n本片以清晨高速道路、緩慢眨眼、方向盤上的細微緊繃、空咖啡杯與輕微車道偏移，呈現長途駕駛中的人體負荷。影片後段轉入休息站，透過下車伸展、慢走、補水、深呼吸與重新聚焦，將事故預防從單一提醒延伸到可被執行的生理重置流程。\nSafe driving depends on stability, recovery, and disciplined timing. A rest stop is therefore not an interruption of the journey; it is part of the safety system that helps the driver return to the road with clearer attention.\nこの作品では、休憩を遅れとして扱わず、安全を支える操作として描く。到着の価値は、速度よりも、身体が制御を取り戻せる条件に近い。",
      "hashtags": "#LongDistanceDriving #DriverFatigue #RoadSafety #HumanFactors #AccidentPrevention #RestArea #DriverWellbeing #FleetSafety #CommercialVehicleSafety #ReactionTime #Hydration #SafeDriving #TransportSafety #YouTubeShorts",
      "reasonZh": "資料支持：長途駕駛風險與疲勞、反應時間、脫水、姿勢固定、注意力窄化、道路單調性與休息不足等條件共同相關；休息、伸展、補水與重新聚焦可作為安全管理中的基本行為層。合理推論：依人因工程與事故預防理論，事故常在可見事件之前累積微小徵兆，本片因此把「距離」重新操作化為身體負荷、反應延遲與風險接近程度。規劃假設：若將休息站設計為安全系統的一部分，商用車影片可同時服務駕駛教育、車隊管理、保險風險溝通與品牌公益形象。行動建議：若後續加入疲勞評分、休息建議或路線提醒等互動模組，需標示 Demo Dataset / Prototype Simulation / Requires human review，並避免把一般安全建議包裝成醫療或法規承諾。",
      "youtubeId": "bM-tJTwJhD4",
      "url": "https://youtube.com/shorts/bM-tJTwJhD4"
    }
  ],
  "glossary": [
    {
      "term": "AIDTAS",
      "zh": "AIDTAS：Attention、Interest、Desire、Trust、Action、Share 的顧客溝通路徑。",
      "en": "AIDTAS: a communication path from Attention and Interest to Desire, Trust, Action, and Share.",
      "ja": "AIDTAS：Attention、Interest、Desire、Trust、Action、Share をつなぐ顧客コミュニケーションの流れ。",
      "definitionZh": "此框架用於安排短影音從吸引注意、建立情境興趣、累積信任，到轉化為討論、洽詢或分享的過程。",
      "definitionEn": "This framework organizes how short videos attract attention, create contextual interest, build trust, and support discussion, inquiry, or sharing.",
      "definitionJa": "ショート動画が注意を集め、情境への関心を生み、信頼を形成し、相談や共有へつながる過程を整理する枠組みです。"
    },
    {
      "term": "STP",
      "zh": "STP：市場區隔、目標市場選擇、品牌定位。",
      "en": "STP: Segmentation, Targeting, and Positioning.",
      "ja": "STP：市場細分化、ターゲティング、ポジショニング。",
      "definitionZh": "用於將商用車需求從單一市場拆解為物流、旅運、福祉、商務與安全治理等不同溝通場景。",
      "definitionEn": "Used to separate commercial vehicle demand into communication contexts such as logistics, passenger transport, welfare mobility, business use, and safety governance.",
      "definitionJa": "商用車需要を物流、旅客、福祉、ビジネス、安全ガバナンスなどのコミュニケーション文脈に分けるために使います。"
    },
    {
      "term": "CBBE",
      "zh": "顧客基礎品牌權益：由品牌知識、品牌聯想與顧客反應所形成的品牌資產。",
      "en": "Customer-Based Brand Equity: brand value formed through brand knowledge, associations, and customer response.",
      "ja": "顧客ベースのブランド・エクイティ：ブランド知識、連想、顧客反応によって形成されるブランド価値。",
      "definitionZh": "本網站以影片、文案與設計說明建立商用車的可靠、安全、照護、效率與公共責任聯想。",
      "definitionEn": "This site uses video, copy, and rationale to build associations around reliability, safety, care, efficiency, and public responsibility.",
      "definitionJa": "本サイトは動画、文案、設計意図を通じて、信頼性、安全、ケア、効率、公共責任の連想を構築します。"
    },
    {
      "term": "Prototype Simulation",
      "zh": "原型模擬：作品集互動原型，並非正式營運資料。",
      "en": "Prototype Simulation: an interactive portfolio prototype, not official operating data.",
      "ja": "プロトタイプ・シミュレーション：作品集用の対話型原型であり、公式運用データではありません。",
      "definitionZh": "所有影片、成本、法規、AI／ADAS 與產品策略描述均需人工審核。",
      "definitionEn": "All video, cost, regulatory, AI/ADAS, and product-strategy content requires human review.",
      "definitionJa": "動画、コスト、法規、AI／ADAS、商品戦略に関する内容は、人による確認が必要です。"
    }
  ]
};
